import fs from 'node:fs/promises'; import path from 'node:path';
const root=process.cwd(), date='2026-10-01';
const docs=[['REG','NiAv_ Modules & Sub-Modules Register v0.4.html','v0.6','v0.7'],['SEC','NiAv_ Security & Anti-Exploitation Plan (V1) v0.4.html','v0.6','v0.7'],['MPL','NiAv_ Universal Master Plan v0.2.html','v0.4','v0.5'],['ZCP','NiAv_ Zero-Cost Strategy Plan (V1) v0.5.html','v0.7','v0.8'],['DSS','NiAv_Data_Schema_Specification_v0.1.html','v0.3','v0.4'],['DB','NiAv_Database_Schema_Document_v0.1.html','v0.3','v0.4'],['FGA','NiAv_Fit-Gap_Analysis_Workaround_Register_v0.1.html','v0.3','v0.4'],['FDD','NiAv_Functional_Design_Document_v0.1.html','v0.3','v0.4'],['FRD','NiAv_Functional_Requirements_Input_Data_v0.1.html','v0.3','v0.4'],['RSP','NiAv_Release_and_Support_Playbook_v0.1.html','v0.3','v0.4'],['RTM','NiAv_Requirements_Traceability_Matrix_v0.1.html','v0.3','v0.4'],['SYNC','NiAv_Sync_Protocol_Specification_v0.1.html','v0.3','v0.4'],['TEST','NiAv_Test_Plan_and_Test_Data_Plan_v0.1.html','v0.3','v0.4'],['UIUX','NiAv_UI_UX_Specification_Document_v0.1.html','v0.3','v0.4'],['UX','NiAv_UX_Specification_v0.2.html','v0.4','v0.5']];
const schema=[['G0-SCH-001','FIFO cost layers / negative stock','stock_cost_layer; stock_movement; last-known-cost fallback; reconciliation audit','D-M5 / D-08 / OD-DB-002'],['G0-SCH-002','Period locks','period_lock with date range, scope, status, unlock reason, actor and audit link','D-M5'],['G0-SCH-003','Bill-wise settlement','bill_allocation with source/settlement lineage, amount, date, status and operation id','FR-M06'],['G0-SCH-004','Tax, HSN and layout profiles','effective-dated tax_rate_hsn plus versioned layout_profile with sync/backup metadata','MPL 7.4 / profiles'],['G0-SCH-005','Record/operation versioning','record version plus operation.base_version and operation.dependencies','SYNC 3/6'],['G0-SCH-006','Trial anchor / denylist','trial_anchor and denylist_entry lifecycle, revoke state and audit evidence','SEC licence controls'],['G0-SCH-007','Voucher-line discount','voucher_line.discount_amount_paise and discount_rate_bps with calculation rule','FRD voucher lines']];
const evidence=[['V-FG-001','SQLCipher/Drift Android 8+','Documentary source attached; Android 8 smoke test pending'],['GST-RND-001','GST rounding','Official rule attached; golden fixture pending'],['V-FG-003','GST/e-invoice/e-way schemas','Official e-way API/schema sources attached; adapter test pending'],['R-04','WhatsApp/email delivery','Official channel limits attached; delivery/checksum test pending'],['D-06','Android Keystore Android 8','Official API source attached; device test pending'],['O-M07','Printer compatibility','Three-printer physical test required'],['O-14/R-13','DPDP obligations','Official Act source attached; control/legal review pending'],['V-FG-003','File-provider/share/restore','Platform test required']];
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const tbl=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const evidenceSection=()=>`<section id="niav-g0-verification-evidence"><h2>G0 Verification Evidence — ${date}</h2><p>Eight verification records are attached in <code>NiAv_G0_Verification_Evidence_Register_v0.1.xlsx</code>. Documentary sources are recorded where available. No execution result is represented as passed until the named fixture, device, adapter or physical test is attached.</p>${tbl(['Record','Subject','Disposition'],evidence)}</section>`;
const schemaSection=()=>`<section id="niav-g0-schema-implementation"><h2>G0 Approved Schema Changes — ${date}</h2><p>The seven owner-approved schema changes below are now part of the DB/DSS baseline and must be implemented through migration, fixture and regression review.</p>${tbl(['ID','Change','Required DB/DSS delta','Source'],schema)}<p>Implementation gate: schema migration scripts, compatibility review, seed/data conversion, rollback plan and test evidence remain required before production release.</p></section>`;
const impactSection=()=>`<section id="niav-g0-rtm-test-impact"><h2>G0 RTM and Test-Plan Impact Review — ${date}</h2>${tbl(['Change','RTM impact','Test impact'],schema.map(r=>[r[0],`Trace ${r[3]} to DB/DSS and affected functional requirement; status: design approved, implementation pending.`,`Add migration, positive, negative, replay/rollback and reconciliation coverage for ${r[1]}.`]))}<p>Evidence records add eight acceptance gates. RTM and test-plan status is “ready for execution”, not “passed”, until the attached evidence register items are closed with execution records.</p></section>`;
const signoff=()=>`<section id="niav-g0-final-signoff"><h2>Final G0 Sign-off — Conditional</h2><p><strong>Decision:</strong> Conditional G0 acceptance of the reconciled design baseline on ${date}. Owner decisions and deferred gates are recorded, the seven schema changes are approved for implementation, and the eight verification records are registered with sources or explicit execution requirements.</p><p><strong>Not yet production-release accepted:</strong> device/printer/adapter/fixture evidence, schema migrations and the resulting regression execution remain open. Final unconditional sign-off requires those records to be attached and the RTM/test plan rerun with passing results.</p></section>`;
const clean=h=>h.replace(/\s*<section id="niav-g0-(?:verification-evidence|schema-implementation|rtm-test-impact|final-signoff)"[\s\S]*?<\/section>\s*/gi,'').replace(/\s*<section id="niav-g0-closeout-log"[\s\S]*?<\/section>\s*/gi,'');
const backup=path.join(root,`niav_g0_closeout_backups_${date.replaceAll('-','')}`); await fs.mkdir(backup,{recursive:true}); const report=[];
for(const [key,file,from,to] of docs){const full=path.join(root,file);let h=await fs.readFile(full,'utf8');await fs.copyFile(full,path.join(backup,file));h=clean(h).replaceAll(from,to);let sec=''; if(key==='DB'||key==='DSS')sec+=schemaSection(); if(key==='RTM'||key==='TEST')sec+=impactSection(); if(key==='SEC'||key==='ZCP'||key==='FGA'||key==='RSP'||key==='MPL'||key==='REG')sec+=evidenceSection(); sec+=signoff(); h=h.replace(/<body[^>]*>/i,m=>m+sec); h=h.replace(/<\/body>/i,`<section id="niav-g0-closeout-log"><h2>Closeout change log</h2>${tbl(['Version','Date','Change'],[[to,date,'G0 closeout: verification evidence register, approved schema delta, RTM/test impact review and conditional sign-off recorded.']])}</section></body>`); await fs.writeFile(full,h,'utf8'); report.push({key,file,version:to});}
await fs.writeFile(path.join(root,'niav_g0_closeout_report_20261001.json'),JSON.stringify({date,documents:report,verificationRecords:8,schemaChanges:7,signoff:'CONDITIONAL'},null,2)); console.log(JSON.stringify({documents:report.length,backup},null,2));
