import fs from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd(), date='2026-10-03';
const targets=['NiAv_ Modules & Sub-Modules Register v0.4.html','NiAv_ Universal Master Plan v0.2.html','NiAv_ Zero-Cost Strategy Plan (V1) v0.5.html','NiAv_Fit-Gap_Analysis_Workaround_Register_v0.1.html','NiAv_Functional_Requirements_Input_Data_v0.1.html','NiAv_Release_and_Support_Playbook_v0.1.html','NiAv_Sync_Protocol_Specification_v0.1.html'];
const backup=path.join(root,'niav_contradiction_correction_backups_20261003'); await fs.mkdir(backup,{recursive:true});
const changes={
 'NiAv_ Modules & Sub-Modules Register v0.4.html':[
  [/Basic TDS\/TCS deduction records and reports \(TBC if needed\)/gi,'TDS/TCS is deferred to a later release; excluded from V1.'],
  [/PF\/ESI statutory file preparation\/export where required source payroll data exists; full payroll engine remains out of scope unless separately confirmed/gi,'PF/ESI and payroll are out of scope for V1.'],
  [/M17\.11 Direct XML\/native file import/gi,'M17.11 Tally/Busy native import — R3 feasibility only'],
  [/Direct read of Tally\/Busy native formats: <strong>not committed<\/strong>; requires feasibility study/gi,'Direct read of Tally/Busy native formats is deferred to R3 feasibility; V1 uses documented Excel templates.'],
  [/TDS\/TCS, voice input, direct native-file import \(if feasible\), advanced analytics/gi,'voice input, TDS/TCS, PF/ESI/payroll and direct native-file import are excluded or deferred; advanced analytics'],
 ],
 'NiAv_ Universal Master Plan v0.2.html':[[/Sales\/Billing/g,'Billing'],[/TDS\/TCS alongside/gi,'TDS/TCS deferred from V1; alongside'],[/TDS\/TCS and PF\/ESI/gi,'TDS/TCS deferred; PF/ESI and payroll out of scope'],[/TDS\/TCS, PF\/ESI/gi,'TDS/TCS deferred; PF/ESI out of scope']],
 'NiAv_ Zero-Cost Strategy Plan (V1) v0.5.html':[[/last-writer-wins/gi,'field merge; host arrival wins on a same-field clash and the loser is logged'],[/TDS\/TCS and PF\/ESI/gi,'TDS/TCS deferred to a later release; PF/ESI and payroll out of scope'],[/TDS\/TCS\/PF\/ESI/gi,'TDS/TCS deferred; PF/ESI and payroll out of scope']],
 'NiAv_Fit-Gap_Analysis_Workaround_Register_v0.1.html':[[/native import/gi,'native import deferred to R3 feasibility; V1 Excel-template import'],[/Tally\/Busy exports mapped/gi,'Tally/Busy data exported to Excel and mapped to the approved template']],
 'NiAv_Functional_Requirements_Input_Data_v0.1.html':[[/mapping Tally\/Busy exports/gi,'mapping approved Excel templates populated from Tally/Busy exports'],[/Tally\/Busy native/gi,'Tally/Busy native formats (R3 feasibility only)'],[/native import/gi,'native import deferred to R3 feasibility']],
 'NiAv_Release_and_Support_Playbook_v0.1.html':[[/Rollback to previous supported APK \+ restore backup if required/gi,'Uninstall the current APK, install the previous APK, then restore the external backup; in-place downgrade is not supported'],[/rollback to previous APK/gi,'uninstall current APK, install previous APK, then restore external backup']],
 'NiAv_Sync_Protocol_Specification_v0.1.html':[[/Last-writer-wins may be used with audit history, subject to final implementation tests\./gi,'Field-by-field merge; on a same-field clash, host arrival wins and the loser is logged.'],[/last-writer-wins/gi,'field merge; host arrival wins on a same-field clash and the loser is logged']]
};
const section=`<section id="niav-g0-body-corrections"><h2>G0 Body-Text Corrections — 2026-10-03</h2><p>Authoritative corrections applied for G0-CON-001 through G0-CON-005. These corrections supersede contradictory historical wording in the active body. Historical change logs remain historical records.</p><ul><li>CON-001: TDS/TCS is later-release; PF/ESI and payroll are out of scope for V1.</li><li>CON-002: Tally/Busy native import is R3 feasibility only; V1 uses approved Excel templates.</li><li>CON-003: rollback is uninstall current APK, install previous APK, restore external backup; in-place downgrade is unsupported.</li><li>CON-004: master-data sync uses field merge; host arrival wins on same-field clash and the loser is logged.</li><li>CON-005: navigation label is Billing.</li></ul></section>`;
for(const file of targets){const full=path.join(root,file);let h=await fs.readFile(full,'utf8');await fs.copyFile(full,path.join(backup,file));for(const [re,val] of (changes[file]||[]))h=h.replace(re,val);h=h.replace(/\s*<section id="niav-g0-body-corrections"[\s\S]*?<\/section>\s*/gi,'');h=h.replace(/<body[^>]*>/i,m=>m+section);await fs.writeFile(full,h,'utf8');}
console.log(JSON.stringify({corrected:targets.length,backup},null,2));
