import fs from 'node:fs/promises';
const files=['NiAv_Release_and_Support_Playbook_v0.1.html','NiAv_Sync_Protocol_Specification_v0.1.html','NiAv_Functional_Requirements_Input_Data_v0.1.html','NiAv_Fit-Gap_Analysis_Workaround_Register_v0.1.html','NiAv_ Modules & Sub-Modules Register v0.4.html','NiAv_UI_UX_Specification_Document_v0.1.html','NiAv_UX_Specification_v0.2.html'];
for(const f of files){let h=await fs.readFile(f,'utf8');
 h=h.replaceAll("Replace 'uninstall current APK, install previous APK, then restore external backup' with: uninstall, install previous APK, restore external backup.","Approved rollback procedure: uninstall the current APK, install the previous APK, then restore the external backup; in-place downgrade is not supported.");
 h=h.replaceAll("Replace 'uninstall current APK, install previous APK, then restore external backup' with: uninstall, install previous APK, restore external backup. In-place downgrade not supported","Approved rollback procedure: uninstall the current APK, install the previous APK, then restore the external backup; in-place downgrade is not supported.");
 h=h.replaceAll('<td>Deferred: owner gate/date required</td>','<td>Rejected: owner rejected voice input for V1</td>');
 for(const [name,ver] of [['Modules &amp; Sub-Modules Register','v0.8'],['Universal Master Plan','v0.6'],['Zero-Cost Strategy Plan','v0.9'],['Security &amp; Anti-Exploitation Plan','v0.7'],['Fit-Gap Analysis &amp; Workaround Register','v0.5'],['Functional Requirements — Input Data &amp; Data Entry','v0.5']]) h=h.replaceAll(`<td>NIAV-${name.includes('Functional')?'FRD':name.includes('Fit-Gap')?'FGA':name.includes('Security')?'SEC':name.includes('Zero-Cost')?'ZCP':name.includes('Universal')?'MPL':'REG'}</td><td>${name}</td><td>v0.5</td>`, `<td>NIAV-${name.includes('Functional')?'FRD':name.includes('Fit-Gap')?'FGA':name.includes('Security')?'SEC':name.includes('Zero-Cost')?'ZCP':name.includes('Universal')?'MPL':'REG'}</td><td>${name}</td><td>${ver}</td>`);
 h=h.replaceAll('NiAv_ Security &amp; Anti-Exploitation Plan (V1) v0.8.html','NiAv_ Security &amp; Anti-Exploitation Plan (V1) v0.7.html').replaceAll('NiAv_ Zero-Cost Strategy Plan (V1) v0.8.html','NiAv_ Zero-Cost Strategy Plan (V1) v0.9.html');
 await fs.writeFile(f,h,'utf8'); }
console.log('remaining refs repaired');
