import fs from 'node:fs/promises';
import { Workbook, SpreadsheetFile } from 'file:///C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs';
const outDir='E:/NiavERP v2 OpenAI/outputs/01a0f1dd-b8a2-7ba3-9346-01abef17f993';
const rows=[
['V-FG-001','SQLCipher/Drift on Android 8+','Documentary source collected; execution still required','https://pub.dev/packages/sqlcipher_flutter_libs','Package API/licence metadata; run Android 8 binding smoke test before closure.'],
['GST-RND-001','GST rounding rules','Documentary source collected; golden fixture still required','https://einvoice6.gst.gov.in/content/wp-content/uploads/2022/07/notification-02-central-tax-english-2020.pdf','Official e-invoice notification supports round-off to max two decimals; attach passing fixture.'],
['V-FG-003','GST/e-invoice/e-way schemas','E-way official schema/API sources collected; adapter execution still required','https://docs.ewaybillgst.gov.in/apidocs/generate-eway-bill.html','Attach exact schema/version and request/response test capture.'],
['R-04','WhatsApp/email APK delivery limits','Official limits collected; delivery/checksum test still required','https://support.google.com/mail/answer/6584?hl=en | https://faq.whatsapp.com/453914586839706/?cms_platform=android&locale=es_LA','Gmail and WhatsApp channel limits recorded; test APK/ZIP/checksum path.'],
['D-06','Android Keystore on Android 8','Official API source collected; device execution still required','https://developer.android.com/reference/java/security/KeyStore.html','Attach Android 8 key generation, wrap and restore result.'],
['O-M07','Printer compatibility','No documentary substitute; physical execution required','Internal test record required','Test three supported ESC/POS/PDF printer paths and attach results.'],
['O-14/R-13','Indian data-protection obligations','Official Act source collected; control/legal review still required','https://www.meity.gov.in/writereaddata/files/Digital%20Personal%20Data%20Protection%20Act%202023.pdf','Map local-only/minimal-collection controls to reviewed source.'],
['V-FG-003','Android file-provider/share/restore','Platform execution required','https://developer.android.com/guide/topics/providers/file-provider','Run target-version backup, restore, share and FileProvider tests; attach capture.']
];
await fs.mkdir(outDir,{recursive:true}); const wb=Workbook.create(); const s=wb.worksheets.add('Verification Evidence');
s.getRange('A1:E1').values=[['Record ID','Verification subject','Status','Source / evidence location','Closure requirement']]; s.getRange(`A2:E${rows.length+1}`).values=rows;
s.showGridLines=false; s.getRange('A1:E1').format={fill:'#17365D',font:{bold:true,color:'#FFFFFF'},wrapText:true}; s.getRange(`A1:E${rows.length+1}`).format={...s.getRange(`A1:E${rows.length+1}`).format,verticalAlignment:'top',wrapText:true}; s.getRange(`A2:C${rows.length+1}`).format.fill='#FFF2CC'; s.getRange('A:A').format.columnWidth=16; s.getRange('B:B').format.columnWidth=34; s.getRange('C:C').format.columnWidth=34; s.getRange('D:D').format.columnWidth=55; s.getRange('E:E').format.columnWidth=65; s.getRange('1:1').format.rowHeight=32; s.freezePanes.freezeRows(1);
wb.recalculate(); const f=await SpreadsheetFile.exportXlsx(wb); await f.save(`${outDir}/NiAv_G0_Verification_Evidence_Register_v0.1.xlsx`); const p=await wb.render({sheetName:'Verification Evidence',autoCrop:'all',scale:1,format:'png'}); await fs.writeFile(`${outDir}/NiAv_G0_Verification_Evidence_Register.png`,new Uint8Array(await p.arrayBuffer())); console.log('created evidence register');
