// NiAvERP ID value objects — Phase 00.
// D-M4: IDs are UUIDv7 TEXT, app-generated. Generation is a later-slice
// concern; these types only enforce non-empty text so unassigned IDs cannot
// flow through repositories. Distinct types keep company scope explicit.
// Traceability: D-M4/OD-DB-001; DECISIONS.md (D-M4).

/// Opaque entity identifier (UUIDv7 text once generated by the app).
class EntityId {
  EntityId(this.value) {
    if (value.isEmpty) {
      throw ArgumentError.value(value, 'value', 'must not be empty');
    }
  }

  final String value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || (other is EntityId && other.value == value);

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'EntityId($value)';
}

/// Opaque company identifier. Every company-owned write carries one
/// (DSS-C-001); the type system keeps it from being swapped with an entity id.
class CompanyId {
  CompanyId(this.value) {
    if (value.isEmpty) {
      throw ArgumentError.value(value, 'value', 'must not be empty');
    }
  }

  final String value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || (other is CompanyId && other.value == value);

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'CompanyId($value)';
}
